name: bpf-ci

on:
  push:
    branches:
     - bpf*

concurrency: 
  group: ci-test-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  VM_Test:
    runs-on: ${{ matrix.runs_on }}
    name: Kernel ${{ matrix.kernel }} on ${{ matrix.runs_on }} with ${{ matrix.toolchain }}
    timeout-minutes: 100
    strategy:
      fail-fast: false
      matrix:
        include:
          - kernel: 'LATEST'
            runs_on: ubuntu-latest
            arch: 'x86_64'
            toolchain: 'gcc'
          - kernel: 'LATEST'
            runs_on: ubuntu-latest
            arch: 'x86_64'
            toolchain: 'llvm-15'
          - kernel: 'LATEST'
            runs_on: z15
            arch: 's390x'
            toolchain: 'gcc'
    env:
      AUTHOR_EMAIL: "$(git log -1 --pretty=\"%aE\")"
      KERNEL: LATEST
      REPO_ROOT: ${{ github.workspace }}
      REPO_PATH: ""
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/vmtest
        with:
          arch: ${{ matrix.arch }}
          toolchain: ${{ matrix.toolchain }}
